intervalSeconds: 60
teamSpeak:
    favoriteUsers: # Filters for specific users. Leave it empty to match all.
        # - foo
        # - bar
    address: # ts.example.com:10011
    username: # foobar
    password: # hunter2
    virtualServerId: # 1
telegram:
    botToken: # myBotToken
    chatId: # -999
    messageId: # 808
    separator: " | "
    zeroUsers: ¯\_(ツ)_/¯
    updateTitle: true # Prepends the chat title with the current amount of online users.
