intervalSeconds: 60

# Use either teamSpeak3 OR teamSpeak6, not both

# teamSpeak3:
#     address: localhost:10011
#     username: serveradmin
#     password: hunter2
#     virtualServerId: 1
#     favoriteUsers: # Filters for specific users. Leave empty to match all.
#         # - foo
#         # - bar

teamSpeak6:
    address: http://localhost:10080
    apiKey: your-api-key-here
    favoriteUsers: # Filters for specific users. Leave empty to match all.
        # - foo
        # - bar

telegram:
    botToken: myBotToken
    chatId: -999
    separator: " | "
    zeroUsers: ¯\_(ツ)_/¯
    updateTitle: true # Prepends the chat title with the current amount of online users.
